# Generated by Django 3.2.25 on 2024-08-06 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_has_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_review', models.TextField(max_length=400, null=True)),
                ('product_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('approved', models.BooleanField(default=True)),
                ('carousel_review', models.BooleanField(default=False)),
                ('featured_image_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_image_url', to='products.product')),
                ('product_name', models.ForeignKey(limit_choices_to={'orderlineitem__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
